# This is a production Dockerfile, for using in Oracle. Not for local development.
FROM php:8.4-fpm

# System dependencies
RUN apt-get update && apt-get install -y \
    git curl libpng-dev libonig-dev libxml2-dev zip unzip \
    && docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd

# Install Composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html

# Copy application
COPY . .

# Tell git to trust the directory
RUN git config --global --add safe.directory /var/www/html

# Composer stability config (IMPORTANT for Docker/CI environments)
RUN composer config -g github-protocols https
RUN composer config -g preferred-install source

# Install PHP dependencies
RUN composer install --no-dev --optimize-autoloader --no-interaction --prefer-source

# Permissions
RUN chown -R www-data:www-data /var/www/html

EXPOSE 9000

CMD ["php-fpm"]
