# We use this in Oracle, not in local development. This is the secondary nginx in the reverse proxy
# setup. This file will be used in the production Nginx docker container (inside TestTrack app).
# The primary Nginx file is in the Oracle server. This primary Nginx will send all relevant requests
# this this secondary Nginx. Requests with /api/ or /sanctum/ or /docs/ will be sent to this
# secondary Nginx. Basically the secondary Nginx triggers Laravel BE.

server {

    # Although the original request from the browser is HTTPS, the primary Nginx will send only HTTP
    # requests to this secondary Nginx. This is why we use port 80 here.
    listen 80;

    # _ is a wildcard for any domain name. Here we don't care about the domain name, that was the job
    # of the primary Nginx.
    server_name _;

    # The Laravel application's public files are located here.
    root /var/www/html/public;

    # Look for index.php or index.html files in the public folder. If found, serve them.
    index index.php index.html;

    # Use these rules for all requests, that have '/'. That means '/', '/api/', '/sanctum/', '/docs/'
    # and any other request that has '/' in it.
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # If the requested file ends in .php, use these rules
    location ~ \.php$ {
        include fastcgi_params;

        # ends PHP requests to your Laravel/PHP container
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}
