# nginx config for the frontend, to be used in the production Nginx docker container, on Oracle
# Not for local development.
# The FE Nginx serves the Vue static/dist files (index.html, index.js, index.css) and handles Vue router.
# Serve real files normally; otherwise give the request to Vue. In production, we have simply three
# dist files: index.html, index.js, index.css. For this we need a server to serve these files.
server {
    listen 80;

    # the dist files (index.html, index.js, index.css) will be here in the FE container,
    root /usr/share/nginx/html;

    # When someone requests a directory (example /), use index.html as the default file.
    index index.html;

    # For all incoming requests that have '/' in their path, use the following rules.
    location / {

        # This makes Vue Router work. Example: the browser requests /tests/15. There is no physical
        # file for this. So, Nginx falls back to index.html.Then Vue starts. And with that Vue Router
        # too. And then Vue Router does its job.
        try_files $uri $uri/ /index.html;
    }
}
