# nginx config for the frontend, to be used in the production Nginx docker container, on Oracle
# Not for local development.
server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
